'use client'

import { motion, useInView } from 'framer-motion'
import { useRef, useState, useEffect, useCallback } from 'react'
import {
  Play,
  Volume2,
  VolumeX,
  Loader2,
  RotateCcw,
  Maximize2,
  Minimize2,
} from 'lucide-react'
import {
  videoSources,
  type VideoSource,
} from '@/lib/video-sources'

type Orientation = 'portrait' | 'landscape'

type Video = {
  id: string
  category: string
  categorySlug: string
  src: string
  poster: string
  duration: number
  width: number
  height: number
  orientation: Orientation
}

/**
 * Hook that resolves video sources to their best available URL.
 * Tries Cloudinary (if a manifest exists from the upload script) first,
 * then falls back to local files in /public/works/.
 */
function useResolvedVideos(): Video[] {
  const [cloudName, setCloudName] = useState<string | null>(null)

  useEffect(() => {
    // Check for a Cloudinary manifest generated by `bun run upload-videos`
    fetch('/works/cloudinary-manifest.json', { cache: 'no-store' })
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (data?.cloudName) setCloudName(data.cloudName)
      })
      .catch(() => {
        /* no manifest — use local files */
      })
  }, [])

  return videoSources.map((v: VideoSource): Video => {
    const portrait = v.height > v.width
    if (cloudName) {
      return {
        id: v.id,
        category: v.category,
        categorySlug: v.categorySlug,
        src: `https://res.cloudinary.com/${cloudName}/video/upload/f_auto,q_auto/${v.cloudinaryPublicId}.mp4`,
        poster: `https://res.cloudinary.com/${cloudName}/video/upload/so_1,f_jpg,q_auto,w_540/${v.cloudinaryPublicId}.jpg`,
        duration: v.duration,
        width: v.width,
        height: v.height,
        orientation: portrait ? 'portrait' : 'landscape',
      }
    }
    return {
      id: v.id,
      category: v.category,
      categorySlug: v.categorySlug,
      src: v.localSrc,
      poster: v.localPoster,
      duration: v.duration,
      width: v.width,
      height: v.height,
      orientation: portrait ? 'portrait' : 'landscape',
    }
  })
}

const categoryOrder = [
  'Talking Head',
  'Motion Graphics',
  'Promotional Edit',
  'Real Estate Drone Edits',
  'Other',
]

// Portrait (9:16) first, then landscape — preserves original order within each group.
const sortPortraitFirst = (arr: Video[]) =>
  [...arr].sort((a, b) =>
    a.orientation === b.orientation
      ? 0
      : a.orientation === 'portrait'
        ? -1
        : 1,
  )

function formatTime(s: number) {
  if (!isFinite(s) || s < 0) s = 0
  const m = Math.floor(s / 60)
  const sec = Math.floor(s % 60)
  return `${m}:${sec.toString().padStart(2, '0')}`
}

type PlayerState = 'idle' | 'loading' | 'playing' | 'paused' | 'ended'

/**
 * Inline video player card. The video plays *inside* its native-aspect-ratio
 * frame — no modal / separate player. The poster thumbnail is shown by
 * default; the play button appears only on hover. Single click starts
 * playback unmuted. A fullscreen toggle expands the frame.
 */
function VideoCard({
  video,
  index,
  isInView,
}: {
  video: Video
  index: number
  isInView: boolean
}) {
  const videoRef = useRef<HTMLVideoElement>(null)
  const frameRef = useRef<HTMLDivElement>(null)
  const [state, setState] = useState<PlayerState>('idle')
  const [progress, setProgress] = useState(0)
  const [currentTime, setCurrentTime] = useState(0)
  const [duration, setDuration] = useState(video.duration)
  const [muted, setMuted] = useState(false)
  const [isFullscreen, setIsFullscreen] = useState(false)
  const [hovered, setHovered] = useState(false)

  const handlePlay = useCallback(() => {
    const v = videoRef.current
    if (!v) return

    if (state === 'idle') {
      setState('loading')
      v.muted = false
      v.volume = 1.0
      const playPromise = v.play()
      if (playPromise) {
        playPromise
          .then(() => setState('playing'))
          .catch(() => {
            v.muted = true
            v.play()
              .then(() => {
                setState('playing')
                setMuted(true)
              })
              .catch(() => setState('idle'))
          })
      }
    } else if (state === 'playing') {
      v.pause()
    } else if (state === 'paused' || state === 'ended') {
      if (state === 'ended') v.currentTime = 0
      v.muted = false
      v.play()
        .then(() => {
          setState('playing')
          setMuted(false)
        })
        .catch(() => {
          v.muted = true
          v.play().then(() => {
            setState('playing')
            setMuted(true)
          })
        })
    }
  }, [state])

  const handlePause = useCallback(() => setState('paused'), [])
  const handleEnded = useCallback(() => {
    setState('ended')
    setProgress(0)
    setCurrentTime(0)
  }, [])

  const handleTimeUpdate = useCallback(() => {
    const v = videoRef.current
    if (!v) return
    const d = v.duration || video.duration
    if (d > 0) {
      setProgress((v.currentTime / d) * 100)
      setCurrentTime(v.currentTime)
    }
  }, [video.duration])

  const handleLoadedMetadata = useCallback(() => {
    const v = videoRef.current
    if (v && v.duration) setDuration(v.duration)
  }, [])

  const toggleMute = useCallback((e: React.MouseEvent) => {
    e.stopPropagation()
    const v = videoRef.current
    if (!v) return
    v.muted = !v.muted
    setMuted(v.muted)
  }, [])

  const restart = useCallback((e: React.MouseEvent) => {
    e.stopPropagation()
    const v = videoRef.current
    if (!v) return
    v.currentTime = 0
    v.muted = false
    v.play().then(() => {
      setState('playing')
      setMuted(false)
    })
  }, [])

  const toggleFullscreen = useCallback((e: React.MouseEvent) => {
    e.stopPropagation()
    const el = frameRef.current
    if (!el) return
    if (!document.fullscreenElement) {
      const req = el.requestFullscreen?.()
      if (req) req.then(() => setIsFullscreen(true)).catch(() => {})
    } else {
      document
        .exitFullscreen?.()
        .then(() => setIsFullscreen(false))
        .catch(() => {})
    }
  }, [])

  useEffect(() => {
    const onFsChange = () => {
      const active = !!document.fullscreenElement
      setIsFullscreen(active && frameRef.current === document.fullscreenElement)
    }
    document.addEventListener('fullscreenchange', onFsChange)
    return () => document.removeEventListener('fullscreenchange', onFsChange)
  }, [])

  const showPoster = state === 'idle'
  const showControls =
    state === 'playing' || state === 'paused' || state === 'ended' || state === 'loading'

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={isInView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.4, delay: index * 0.04, ease: [0.22, 1, 0.36, 1] }}
      className="mb-6 break-inside-avoid"
    >
      <div
        ref={frameRef}
        className="group relative rounded-2xl overflow-hidden bg-black cursor-pointer select-none"
        style={{ aspectRatio: `${video.width} / ${video.height}` }}
        onClick={handlePlay}
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
        role="button"
        tabIndex={0}
        aria-label={`Play ${video.category} video`}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault()
            handlePlay()
          }
        }}
      >
        {/* Video element — always rendered so it can play inline.
            object-contain in fullscreen (no cropping), object-cover otherwise. */}
        <video
          ref={videoRef}
          src={video.src}
          poster={showPoster ? video.poster : undefined}
          preload="none"
          playsInline
          onPlay={() => setState('playing')}
          onPause={handlePause}
          onEnded={handleEnded}
          onTimeUpdate={handleTimeUpdate}
          onLoadedMetadata={handleLoadedMetadata}
          onWaiting={() => setState('loading')}
          onPlaying={() => setState('playing')}
          onCanPlay={() => {
            if (state === 'loading') setState('playing')
          }}
          className={`w-full h-full ${
            isFullscreen ? 'object-contain' : 'object-cover'
          }`}
        />

        {/* Idle: clean poster; play button + border appear only on hover */}
        {showPoster && (
          <>
            {/* subtle dark overlay on hover */}
            <div
              className={`absolute inset-0 transition-colors duration-300 ${hovered ? 'bg-black/30' : 'bg-black/0'}`}
            />
            {/* play button — hidden until hover */}
            <div
              className={`absolute inset-0 flex items-center justify-center transition-opacity duration-300 ${hovered ? 'opacity-100' : 'opacity-0'}`}
            >
              <div className="w-16 h-16 rounded-full flex items-center justify-center bg-brand shadow-[0_0_30px_rgba(255,247,0,0.5)]">
                <Play className="w-6 h-6 text-black ml-1" fill="black" />
              </div>
            </div>
            {/* yellow border on hover */}
            <div
              className={`absolute inset-0 rounded-2xl border-2 border-brand transition-opacity duration-300 pointer-events-none ${hovered ? 'opacity-100' : 'opacity-0'}`}
            />
          </>
        )}

        {/* Loading spinner */}
        {state === 'loading' && (
          <div className="absolute inset-0 flex items-center justify-center bg-black/40">
            <Loader2 className="w-10 h-10 text-brand animate-spin" />
          </div>
        )}

        {/* Playing / paused / ended overlay controls */}
        {showControls && state !== 'loading' && (
          <>
            {/* Top gradient + time + controls */}
            <div className="absolute top-0 inset-x-0 p-3 bg-gradient-to-b from-black/70 to-transparent flex items-center justify-between z-10">
              <span className="text-white/90 text-xs font-medium tabular-nums">
                {formatTime(currentTime)} / {formatTime(duration)}
              </span>
              <div className="flex items-center gap-2">
                <button
                  onClick={toggleMute}
                  className="w-8 h-8 rounded-full bg-white/15 hover:bg-white/25 flex items-center justify-center transition-colors"
                  aria-label={muted ? 'Unmute' : 'Mute'}
                >
                  {muted ? (
                    <VolumeX className="w-4 h-4 text-white" />
                  ) : (
                    <Volume2 className="w-4 h-4 text-white" />
                  )}
                </button>
                <button
                  onClick={toggleFullscreen}
                  className="w-8 h-8 rounded-full bg-white/15 hover:bg-white/25 flex items-center justify-center transition-colors"
                  aria-label={isFullscreen ? 'Exit fullscreen' : 'Fullscreen'}
                >
                  {isFullscreen ? (
                    <Minimize2 className="w-4 h-4 text-white" />
                  ) : (
                    <Maximize2 className="w-4 h-4 text-white" />
                  )}
                </button>
              </div>
            </div>

            {/* Center play/pause/replay */}
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
              {state === 'paused' && (
                <div className="w-14 h-14 rounded-full flex items-center justify-center bg-brand/90">
                  <Play className="w-5 h-5 text-black ml-0.5" fill="black" />
                </div>
              )}
              {state === 'ended' && (
                <div
                  className="pointer-events-auto w-14 h-14 rounded-full flex items-center justify-center bg-brand/90 cursor-pointer"
                  onClick={restart}
                >
                  <RotateCcw className="w-5 h-5 text-black" />
                </div>
              )}
            </div>

            {/* Bottom progress bar */}
            <div className="absolute bottom-0 inset-x-0 px-3 pb-2 pt-6 bg-gradient-to-t from-black/70 to-transparent z-10">
              <div
                className="h-1.5 rounded-full bg-white/20 overflow-hidden cursor-pointer"
                onClick={(e) => {
                  e.stopPropagation()
                  const v = videoRef.current
                  if (!v) return
                  const rect = e.currentTarget.getBoundingClientRect()
                  const pct = (e.clientX - rect.left) / rect.width
                  v.currentTime = pct * (v.duration || video.duration)
                }}
              >
                <div
                  className="h-full bg-brand rounded-full transition-[width] duration-150"
                  style={{ width: `${progress}%` }}
                />
              </div>
            </div>
          </>
        )}
      </div>

      {/* Category label below the frame */}
      <div className="mt-3 text-center">
        <span className="text-xs font-medium tracking-wide text-brand uppercase">
          {video.category}
        </span>
      </div>
    </motion.div>
  )
}

export default function Works() {
  const [activeCategory, setActiveCategory] = useState<string>('All')
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, margin: '-100px' })
  // Resolves to Cloudinary CDN URLs if a manifest exists, else local files
  const resolvedVideos = useResolvedVideos()

  const categories = ['All', ...categoryOrder]

  const filteredVideos =
    activeCategory === 'All'
      ? sortPortraitFirst(resolvedVideos)
      : sortPortraitFirst(resolvedVideos.filter((v) => v.category === activeCategory))

  return (
    <section
      id="works"
      className="py-24 lg:py-32 bg-muted/30 relative overflow-hidden"
    >
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        {/* Header */}
        <motion.div
          ref={ref}
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
          className="text-center mb-12"
        >
          <p className="text-sm font-medium tracking-[0.2em] uppercase mb-4 text-brand">
            Portfolio
          </p>
          <h2 className="text-4xl lg:text-5xl xl:text-6xl font-bold text-foreground tracking-tight">
            Selected Works
          </h2>
        </motion.div>

        {/* Category Filters */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.2, ease: [0.22, 1, 0.36, 1] }}
          className="flex flex-wrap justify-center gap-2 mb-12"
        >
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => setActiveCategory(category)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-all duration-300 ${
                activeCategory === category
                  ? 'text-black bg-brand'
                  : 'bg-foreground/5 text-muted-foreground hover:bg-foreground/10'
              }`}
            >
              {category}
            </button>
          ))}
        </motion.div>

        {/* Masonry grid — handles mixed aspect ratios (portrait + landscape).
            Portrait (9:16) videos render first, then landscape. */}
        <div
          key={activeCategory}
          className="columns-1 sm:columns-2 lg:columns-3 xl:columns-4 [column-gap:1.5rem]"
        >
          {filteredVideos.map((video, index) => (
            <VideoCard
              key={video.id}
              video={video}
              index={index}
              isInView={isInView}
            />
          ))}
        </div>
      </div>
    </section>
  )
}
